### ISSUE TITLE
Append(Insert) method test is failed for complicated insertion

### ISSUE THREAD

**Issue by rojaster** [PyCQA/redbaron#139]
As I got it,  we have a problem when working with complicated insertion. Essentially, if two excerpts of the code had been merged, it wouldn't get an exception. 
I've been digging around the problem a little, but haven't looked at carefully. 

Test code is attached below. 

```python
from tempfile import NamedTemporaryFile, gettempdir
import textwrap
import redbaron
import os
from redbaron import RedBaron


redbaron.DEBUG = False

target_file = NamedTemporaryFile(mode="w+", delete=True, suffix="_rb_test_inserter", dir=gettempdir())
file_with_insertion = NamedTemporaryFile(mode="w+", delete=True, suffix="_rb_test_inserter", dir=gettempdir())

target_file.write("\n#!/usr/bin/env python\n#! -*- coding: utf-8 -*-\na = 1\n")
file_with_insertion.write("def a():\n    pass")

target_file.seek(0)
file_with_insertion.seek(0)

t_buffer = target_file.read()
i_buffer = file_with_insertion.read()

target_file.close()
file_with_insertion.close()

# if os.getenv('PYCHARM_HOSTED'):
#     if os.getenv('IPYTHONENABLE'):
#         print("IPYTHONENABLE %s" % os.getenv('IPYTHONENABLE'))
#     print("PYCHARM_HOSTED : {0}".format(os.getenv('PYCHARM_HOSTED')))
# if not os.getenv('PYCHARM_HOSTED'):
#     if __IPYTHON__:
#         print("IPYTHOSHELL %s" % __IPYTHON__)

mixed_code_buffer = textwrap.dedent(u"""
def some_method(a=1):
    def some_method1(b=0):
        return b+a
    return some_method1(a)
""")

rbt = RedBaron("a = 1")
rbi = RedBaron(i_buffer)
rbm_mixed_code_buffer = RedBaron(mixed_code_buffer)

print("Target================")
print(rbt.dumps())
print("Insertion=============")
print(rbi.dumps())

rbt.append(rbi.dumps())
print("Result================")
print(rbt.dumps())

print("Mixed code ========")
print(rbm_mixed_code_buffer.dumps())

print("After adding mixed code ========")
rbt.append(rbm_mixed_code_buffer)
print(rbt.dumps())
``` 

Traceback of the error
```bash
/home/alekum/.virtualenvs/redbaron/bin/python /home/alekum/Development/PythonPlayground/redbaron/rbtestappend.py
Target================
a = 1
Insertion=============
def a():
    pass

Result================
a = 1
def a():
    pass

Mixed code ========

def some_method(a=1):
    def some_method1(b=0):
        return b+a
    return some_method1(a)

After adding mixed code ========
Traceback (most recent call last):
  File "/home/alekum/Development/PythonPlayground/redbaron/rbtestappend.py", line 68, in <module>
    rbt.append(rbm_mixed_code_buffer)
  File "/home/alekum/Development/redbaron/redbaron/base_nodes.py", line 1379, in append
    self.insert(len(self), value)
  File "/home/alekum/Development/redbaron/redbaron/base_nodes.py", line 1374, in insert
    value = self._convert_input_to_node_object(value, parent=self.node_list, on_attribute=self.on_attribute)
  File "/home/alekum/Development/redbaron/redbaron/redbaron.py", line 60, in _convert_input_to_node_object
    return base_nodes.GenericNodesUtils._convert_input_to_node_object(self, value, self, "root")
  File "/home/alekum/Development/redbaron/redbaron/base_nodes.py", line 166, in _convert_input_to_node_object
    raise NotImplementedError
NotImplementedError
```

**Comment by rojaster** [comment]
Sorry, forgot to attach a version of RedBaron: 8fecf13cd564c186706d41747ffcd6471750e6ef Merge pull request #133 from jwilk/spelling , that was last commit on master that I've pulled in
