### ISSUE TITLE
Node.decrease_indentation does not work

### ISSUE THREAD

**Issue by swolchok** [PyCQA/redbaron#64]
Strings can only be added, not subtracted:

```
>>> RedBaron('''
... f(a=b,
...     c=d)''').find_all('call_argument').map(lambda x: x.decrease_indentation(2))
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Library/Python/2.7/site-packages/redbaron.py", line 386, in map
    return NodeList([function(x) for x in self.data])
  File "<stdin>", line 3, in <lambda>
  File "/Library/Python/2.7/site-packages/redbaron.py", line 1010, in decrease_indentation
    self.get_indentation_node().indent -= number_of_spaces * " "
TypeError: unsupported operand type(s) for -=: 'str' and 'str'
```

**Comment by Psycojoker** [comment]
Hello,

Thanks for reporting, I've pushed a fix for it, it will be in the next release.

I'm surprised that I've forgot to test this one.

Kind regards,

**Comment by Psycojoker** [comment]
(actually fixed on master)

**Comment by ibizaman** [comment]
I'm closing this since it's fixed on master. @swolchok do not hesitate to reopen this issue if you still encounter problems.
